name: Build api-inference documentation

on:
  push:
    paths:
      - "docs/api-inference/**"
    branches:
      - main

jobs:
   build:
    uses: huggingface/doc-builder/.github/workflows/build_main_documentation.yml@main
    with:
      commit_sha: ${{ github.sha }}
      package: hub-docs
      package_name: api-inference
      path_to_docs: hub-docs/docs/api-inference/
      additional_args: --not_python_module
    secrets:
      token: ${{ secrets.HUGGINGFACE_PUSH }}
